#!/usr/bin/env node

/**
 * Notification module for HBL Deals & Discounts
 * Sends deal summaries via Email (Nodemailer) and WhatsApp (Twilio).
 */

const nodemailer = require("nodemailer");
const path = require("path");
const fs = require("fs");

// Load .env from project root
require("dotenv").config({ path: path.join(__dirname, "..", ".env") });

const DATA_FILE = path.join(__dirname, "..", "data", "deals.json");

function loadDeals() {
  if (!fs.existsSync(DATA_FILE)) {
    throw new Error(`No deals data found at ${DATA_FILE}. Run the scraper first.`);
  }
  return JSON.parse(fs.readFileSync(DATA_FILE, "utf-8"));
}

function formatDealsText(data) {
  const { filters, totalDeals, deals, scrapedAt } = data;
  const date = new Date(scrapedAt).toLocaleString();

  let text = `🏦 HBL Deals & Discounts\n`;
  text += `📍 City: ${filters.city}\n`;
  text += `💳 Card: ${filters.card}\n`;
  text += `📅 Scraped: ${date}\n`;
  text += `📊 Total Deals: ${totalDeals}\n`;
  text += `${"─".repeat(40)}\n\n`;

  deals.forEach((deal, i) => {
    text += `${i + 1}. ${deal.merchantName}\n`;
    text += `   🏷️ Discount: ${deal.discount}\n`;
    text += `   📅 Valid: ${deal.validDays}\n`;
    text += `   💰 Max Cap: ${deal.maxCap}\n`;
    if (deal.category) text += `   📂 Category: ${deal.category}\n`;
    text += `\n`;
  });

  return text;
}

function formatDealsHTML(data) {
  const { filters, totalDeals, deals, scrapedAt } = data;
  const date = new Date(scrapedAt).toLocaleString();

  let html = `
  <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <div style="background: linear-gradient(135deg, #00653e, #00a651); color: white; padding: 20px; border-radius: 12px 12px 0 0;">
      <h1 style="margin: 0; font-size: 24px;">🏦 HBL Deals & Discounts</h1>
      <p style="margin: 8px 0 0; opacity: 0.9;">📍 ${filters.city} | 💳 ${filters.card}</p>
      <p style="margin: 4px 0 0; opacity: 0.7; font-size: 12px;">Scraped: ${date}</p>
    </div>
    <div style="background: #f8f9fa; padding: 12px 20px; border-bottom: 1px solid #e9ecef;">
      <strong>${totalDeals} deals found</strong>
    </div>
    <table style="width: 100%; border-collapse: collapse; background: white;">
      <thead>
        <tr style="background: #e9ecef;">
          <th style="padding: 10px; text-align: left; font-size: 13px;">#</th>
          <th style="padding: 10px; text-align: left; font-size: 13px;">Merchant</th>
          <th style="padding: 10px; text-align: left; font-size: 13px;">Discount</th>
          <th style="padding: 10px; text-align: left; font-size: 13px;">Day</th>
          <th style="padding: 10px; text-align: left; font-size: 13px;">Max Cap</th>
        </tr>
      </thead>
      <tbody>`;

  deals.forEach((deal, i) => {
    const bgColor = i % 2 === 0 ? "#ffffff" : "#f8f9fa";
    html += `
        <tr style="background: ${bgColor}; border-bottom: 1px solid #e9ecef;">
          <td style="padding: 10px; font-size: 13px;">${i + 1}</td>
          <td style="padding: 10px; font-size: 13px; font-weight: 600;">${deal.merchantName}</td>
          <td style="padding: 10px; font-size: 13px; color: #00a651; font-weight: 700;">${deal.discount}</td>
          <td style="padding: 10px; font-size: 13px;">${deal.validDays}</td>
          <td style="padding: 10px; font-size: 13px;">${deal.maxCap}</td>
        </tr>`;
  });

  html += `
      </tbody>
    </table>
    <div style="background: #f8f9fa; padding: 12px 20px; border-radius: 0 0 12px 12px; text-align: center; color: #6c757d; font-size: 12px;">
      Generated by HBL Deals Scraper
    </div>
  </div>`;

  return html;
}

async function sendEmail(data) {
  const {
    SMTP_HOST,
    SMTP_PORT,
    SMTP_USER,
    SMTP_PASS,
    EMAIL_FROM,
    EMAIL_TO,
  } = process.env;

  if (!SMTP_HOST || !SMTP_USER || !SMTP_PASS || !EMAIL_TO) {
    console.log("⚠️  Email not configured. Set SMTP_HOST, SMTP_USER, SMTP_PASS, EMAIL_TO in .env");
    return false;
  }

  console.log(`📧 Sending email to ${EMAIL_TO}...`);

  const transporter = nodemailer.createTransport({
    host: SMTP_HOST,
    port: parseInt(SMTP_PORT || "587"),
    secure: (SMTP_PORT || "587") === "465",
    auth: {
      user: SMTP_USER,
      pass: SMTP_PASS,
    },
  });

  const mailOptions = {
    from: EMAIL_FROM || SMTP_USER,
    to: EMAIL_TO,
    subject: `🏦 HBL Deals - ${data.filters.city} | ${data.totalDeals} deals (${new Date().toLocaleDateString()})`,
    text: formatDealsText(data),
    html: formatDealsHTML(data),
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log(`✅ Email sent: ${info.messageId}`);
    return true;
  } catch (error) {
    console.error(`❌ Email failed: ${error.message}`);
    return false;
  }
}

async function sendWhatsApp(data) {
  const {
    TWILIO_ACCOUNT_SID,
    TWILIO_AUTH_TOKEN,
    TWILIO_WHATSAPP_FROM,
    WHATSAPP_TO,
  } = process.env;

  if (!TWILIO_ACCOUNT_SID || !TWILIO_AUTH_TOKEN || !WHATSAPP_TO) {
    console.log("⚠️  WhatsApp not configured. Set TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, WHATSAPP_TO in .env");
    return false;
  }

  console.log(`📱 Sending WhatsApp message to ${WHATSAPP_TO}...`);

  try {
    const client = require("twilio")(TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN);

    const messageText = formatDealsText(data);

    // Twilio WhatsApp has a 1600 char limit per message, split if needed
    const chunks = [];
    const lines = messageText.split("\n");
    let currentChunk = "";

    for (const line of lines) {
      if ((currentChunk + line + "\n").length > 1500) {
        chunks.push(currentChunk);
        currentChunk = line + "\n";
      } else {
        currentChunk += line + "\n";
      }
    }
    if (currentChunk.trim()) chunks.push(currentChunk);

    const fromNumber = TWILIO_WHATSAPP_FROM || "whatsapp:+14155238886";

    for (let i = 0; i < chunks.length; i++) {
      const msg = await client.messages.create({
        body: chunks[i],
        from: fromNumber,
        to: `whatsapp:${WHATSAPP_TO}`,
      });
      console.log(`✅ WhatsApp message ${i + 1}/${chunks.length} sent: ${msg.sid}`);
    }

    return true;
  } catch (error) {
    console.error(`❌ WhatsApp failed: ${error.message}`);
    return false;
  }
}

async function notifyAll(options = {}) {
  const { email = true, whatsapp = true } = options;
  const data = loadDeals();

  console.log(`\n📬 Sending notifications for ${data.totalDeals} deals...\n`);

  const results = {};

  if (email) {
    results.email = await sendEmail(data);
  }

  if (whatsapp) {
    results.whatsapp = await sendWhatsApp(data);
  }

  return results;
}

// CLI entry point
if (require.main === module) {
  const args = process.argv.slice(2);
  const options = {
    email: !args.includes("--no-email"),
    whatsapp: !args.includes("--no-whatsapp"),
  };

  notifyAll(options)
    .then((results) => {
      console.log("\n📊 Notification results:", results);
    })
    .catch((err) => {
      console.error("Failed:", err.message);
      process.exit(1);
    });
}

module.exports = { notifyAll, sendEmail, sendWhatsApp, formatDealsText, formatDealsHTML };
